{% set version = "0.26.1" %}

package:
  name: gym
  version: {{ version }}

source:
  url: https://github.com/openai/gym/archive/refs/tags/{{ version }}.tar.gz
  sha256: bff4d02892e73091b40bc82d67f0007f46926cb7ab91ffff3b048395ec321a83

build:
  number: 0

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

outputs:
  - name: gym
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - python
        - pip
        - cloudpickle >=1.2.0
        - numpy
      run:
        - python
        - cloudpickle >=1.2.0
        - numpy
        - importlib_metadata >=4.8.1  # [py<=39]
    test:
      imports:
        - gym

  - name: gym-all
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym-atari', exact=True) }}
        - {{ pin_subpackage('gym-box2d', exact=True) }}
        - {{ pin_subpackage('gym-classic_control', exact=True) }}
        - {{ pin_subpackage('gym-mujoco', exact=True) }}
        # see below
        # - {{ pin_subpackage('gym-mujoco_py', exact=True) }}
        - {{ pin_subpackage('gym-toy_text', exact=True) }}
        - {{ pin_subpackage('gym-other', exact=True) }}
    test:
      source_files:
        - tests/
      requires:
        - mock
        - pytest
        - pip
      commands:
        - pip check
        - pytest -v tests/

  - name: gym-atari
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - ale-py >=0.8.0,<0.9
    test:
      imports:
        - gym.envs.atari

  - name: gym-box2d
    requirements:
      host:
        - python
        - swig ==4.*
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - box2d-py ==2.3.*
        - pygame ==2.1.*
    test:
      imports:
        - gym.envs.box2d

  - name: gym-classic_control
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - pygame ==2.1.*
    test:
      imports:
        - gym.envs.classic_control

  - name: gym-mujoco
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - mujoco-python ==2.2.0
        - imageio >=2.14.1
    test:
      imports:
        - gym.envs.mujoco

  - name: gym-mujoco_py
    build:
      # we currently don't have https://github.com/openai/mujoco-py
      # in conda-forge, and it'll be replaced by mujoco anyway
      skip: true
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - mujoco-py >=2.1,<2.2
        - imageio >=2.14.1
    test:
      imports:
        - gym.envs.mujoco

  - name: gym-toy_text
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - pygame ==2.1.*
    test:
      imports:
        - gym.envs.toy_text

  - name: gym-other
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - lz4 >=3.1.0
        - matplotlib >=3.0
        - moviepy >=1.0
        - py-opencv >=3.0
    test:
      imports:
        # There are no tests in the source code for gym-other

about:
  home: https://github.com/openai/gym
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.'
  description: 'The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.'
  doc_url: https://gym.openai.com/docs/
  dev_url: https://github.com/openai/gym

extra:
  recipe-maintainers:
    - h-vetinari
    - jkterry1
    - pseudo-rnd-thoughts
    - thewchan
