{% set name = "gymnasium" %}
{% set version = "1.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Farama-Foundation/Gymnasium/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 600df166dd6aca13281130a80eff1a23f4f867a5c919ed614743806e7e5efeaa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=61.0.0
  run:
    - python
    - numpy >=1.21.0
    - cloudpickle >=1.2.0
    - typing_extensions >=4.3.0
    - farama-notifications >=0.0.1
  run_constrained:
    # atari
    - ale_py >=0.9
    # box2d / classic-control / toy-text
    - box2d ==2.3.10
    - pygame-ce >=2.1.3
    - swig ==4.*
    # mujoco
    - mujoco >=2.1.5
    - imageio >=2.14.1
    - packaging >=23.0
    # jax
    - jax >=0.4.16
    - jaxlib >=0.4.16
    - flax >=0.5.0
    - array-api-compat >=1.11.0
    # torch
    - pytorch >=1.13.0
    # other
    - moviepy >=1.0.0
    - matplotlib-base >=3.0
    - opencv-python >=3.0
    - seaborn >=0.13

test:
  source_files:
    - tests
  imports:
    - gymnasium
  commands:
    - pip check
    - pytest -v tests/test_core.py
  requires:
    - pip
    - pytest

about:
  home: https://farama.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A standard API for reinforcement learning and a diverse set of reference environments (formerly Gym)
  description: |
    Gymnasium is an open source Python library for developing and comparing reinforcement learning algorithms 
    by providing a standard API to communicate between learning algorithms and environments, 
    as well as a standard set of environments compliant with that API. 
    This is a fork of OpenAI's Gym library by the maintainers 
    (OpenAI handed over maintenance a few years ago to an outside team), and is where future maintenance will occur going forward
  dev_url: https://github.com/Farama-Foundation/Gymnasium
  doc_url: https://gymnasium.farama.org

extra:
  recipe-maintainers:
    - h-vetinari
    - pseudo-rnd-thoughts
    - thewchan
  feedstock-name: gymnasium
