{% set version = "0.22.0" %}

package:
  name: gym
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gym/gym-{{ version }}.tar.gz
  sha256: 339144c89951758187c378111919bc0e2f1695f9e9d9699e3f19279a6398148d

build:
  number: 0

# Need these up here for conda-smithy to handle them properly.
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

outputs:
  - name: gym
    build:
      script: {{ PYTHON }} -m pip install . -vv --no-deps
    requirements:
      host:
        - python
        - pip
        - cloudpickle >=1.2.0
        - numpy
      run:
        - python
        - cloudpickle >=1.2.0
        - numpy
        - importlib_metadata >=4.8.1  # [py<=39]
    test:
      imports:
        - gym

  - name: gym-all
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym-atari', exact=True) }}
        - {{ pin_subpackage('gym-box2d', exact=True) }}
        - {{ pin_subpackage('gym-classic_control', exact=True) }}
        - {{ pin_subpackage('gym-mujoco', exact=True) }}
        - {{ pin_subpackage('gym-toy_text', exact=True) }}
        - {{ pin_subpackage('gym-other', exact=True) }}
    test:
      source_files:
        - tests/
      requires:
        - mock
        - pytest
        - pip
      commands:
        - pip check
        - pytest -v tests/

  - name: gym-atari
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - ale-py >=0.7.4
    test:
      imports:
        - gym.envs.atari

  - name: gym-box2d
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - box2d-py ==2.3.*
        - pygame ==2.1.*
    test:
      imports:
        - gym.envs.box2d

  - name: gym-classic_control
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - pygame ==2.1.*
    test:
      imports:
        - gym.envs.classic_control

  - name: gym-mujoco
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        # conda-forge builds for mujoco-python start only from 2.2.0
        - mujoco-python
        - imageio
    test:
      imports:
        - gym.envs.mujoco

  - name: gym-toy_text
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - pygame ==2.1.*
        - scipy >=1.4.1
    test:
      imports:
        - gym.envs.toy_text

  - name: gym-other
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('gym', exact=True) }}
        - lz4 >=3.1.0
        - opencv >=3.0
    test:
      imports:
        # There are no tests in the source code for gym-other

about:
  home: https://github.com/openai/gym
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.'
  description: 'The OpenAI Gym: A toolkit for developing and comparing your reinforcement learning agents.'
  doc_url: https://gym.openai.com/docs/
  dev_url: https://github.com/openai/gym

extra:
  recipe-maintainers:
    - h-vetinari
    - jkterry1
    - pseudo-rnd-thoughts
    - thewchan
